/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memories shared with everyone on this workbench, newest first */
        get: operations["getMemories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memories/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a shared memory without allowing save replays to recreate it */
        delete: operations["deleteMemory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shared coordinator chat archive, newest first */
        get: operations["getChatArchive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import browser archives without replacing coordinator chats */
        post: operations["importChatArchive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clone the sandbox and coordinator transcript into a new chat */
        post: operations["postFork"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whether this backend is token-protected, and whether you are in
         * @description Open to unauthenticated callers. `auth_required` is false for local development (no control token configured); in the E2B template start.sh always writes one, so it is true there.
         */
        get: operations["getAuthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a control or launch token for a session cookie
         * @description Accepts the sandbox's persistent control token, or a single-use launch token (the `#token=` fragment of the URL printed in the sandbox terminal). On success sets a 12-hour HttpOnly SameSite=Strict cookie.
         */
        post: operations["postAuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear this browser's session cookie */
        post: operations["postAuthLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a single-use share link for another person
         * @description Returns a URL carrying a launch token that expires in 10 minutes and can be redeemed once. Everyone who redeems one shares this backend's keys, sandboxes and chats — shared access, not multi-tenancy.
         */
        post: operations["postAuthInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe + credential presence
         * @description Reports whether the backend currently holds each credential (never the values). The frontend key gate opens when either flag is false — the in-sandbox template ships with no keys baked in.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Supply credentials at runtime (key gate)
         * @description Accepts either or both keys after boot. They are held in process memory/env only — never persisted or logged. Blank/omitted fields leave the current value untouched.
         */
        post: operations["postKeys"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Selectable Agents API models
         * @description Live proxy of OpenAI's GET /v1/models, filtered to the gpt-5.5 / gpt-5.6 agent ids (bare or -sol/-luna; codex ids fail self-hosted turns) plus known-good ids the listing omits, cached in-process for an hour. Empty list when no OpenAI key is configured yet; the frontend decorates ids with display names and capability icons.
         */
        get: operations["getModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configured field markers for credentials saved in app memory */
        get: operations["getMcpCredentials"];
        put?: never;
        /** Save reusable MCP credentials in workbench memory */
        post: operations["saveMcpCredentials"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save MCPs and reconnect now or after the active turn, preserving workspace and transcript */
        post: operations["setMcpSelection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Selectable MCP servers
         * @description The picker's catalog: every MCP server this build can attach (a few hand-listed ones plus all of E2B's hosted catalog), the config fields each accepts, and the selection a brand-new chat starts from. Static metadata, no upstream call and no keys. A `service` server is dialled over HTTP by the Agents API itself; an `environment` server is spawned as a stdio subprocess inside the sandbox; a `gateway` server runs behind mcp-gateway in the sandbox with the chat's option values.
         */
        get: operations["getMcpServers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot of one chat's backend session */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run one agent turn, streamed as Server-Sent Events
         * @description Creates the Agents API session + E2B sandbox on first use, then streams the turn. Each SSE `data:` line is one JSON-encoded ChatEvent; comment lines (`: keepalive`) are heartbeats. The stream closes after a terminal event (done / cancelled / error), optionally followed by a usage event.
         */
        post: operations["postChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Replay and follow one chat's process logs
         * @description Long-lived SSE stream independent of /api/chat. Replays bounded in-memory history after cursor, then follows backend errors, executor stdout/stderr, and Agents command output. Comment frames are heartbeats.
         */
        get: operations["getLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reattach a chat's backend context (pauses the other chats)
         * @description Pauses every other live chat's sandbox, then resumes this chat: the upstream Agents API session is verified (retrieve) and the E2B sandbox is resumed — or recreated — with the executor re-registered. Returns expired=true when the upstream session is gone; the chat is then only a read-only thread whose retained workspace can be recovered by forking.
         */
        post: operations["postResume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Snapshot one chat's sandbox now (auto-pause-after-turn toggle)
         * @description Pauses the chat's sandbox immediately (billing stops; the next message or resume reattaches it). No-op when the chat has no live sandbox; refuses while a turn is running.
         */
        post: operations["postPause"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/steer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a text interjection to the active root turn
         * @description Deduplicated by chat and submission ID. The upstream lifecycle-finalization and parent-guarded runtime-write conflicts are retried for up to 15 seconds. The same input and upstream Idempotency-Key are reused for runtime-write conflicts; lifecycle-finalization conflicts explicitly require a fresh key. Accepted or ambiguous deliveries are never resent. Other rejections are not retried. Stop cancels pending retries.
         */
        post: operations["postSteer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel the active turn */
        post: operations["postCancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tear down the session (kills the sandbox, discards the key) */
        post: operations["postReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the sandbox workspace tree */
        get: operations["getFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one workspace file (UTF-8 text ≤256 KB, or an image ≤4 MB) */
        get: operations["getFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload files into the sandbox workspace (drop zone)
         * @description Writes each multipart file into /workspace via sandbox.files.write. Any file type is accepted; the whole request body is capped at 100 MB. Refuses while the chat's sandbox is paused.
         */
        post: operations["postUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ArchivedChat: {
            capabilities?: components["schemas"]["Capabilities"];
            id: string;
            title: string;
            createdAt: number;
            updatedAt: number;
            turns: components["schemas"]["ArchivedTurn"][];
            expired?: boolean;
            forkable?: boolean;
            sandboxId?: string | null;
            sessionId?: string | null;
            parentChatId?: string | null;
        };
        SteerRequest: {
            chat_id: string;
            /** @description Display-only poster identifier, not authenticated identity. */
            client_id: string;
            text: string;
            /** @description Client-generated ID stable across retries, scoped to this chat. */
            submission_id: string;
        };
        Interjection: {
            /** @description Unicode code point offset in the redacted assistant text when this submission was admitted. Preserved through status updates, reload, and fork. Absent or null for older records. */
            text_offset?: number | null;
            submission_id: string;
            text: string;
            /** @enum {string} */
            status: "sending" | "posted" | "confirmed" | "became_turn" | "unconfirmed" | "refused" | "cancelled";
            /** @description Submission time in Unix milliseconds. */
            at: number;
            /** @description Display-only client ID of the poster. */
            by: string;
            detail?: string | null;
        };
        ArchivedTurn: {
            id: number;
            upstreamTurnId?: string;
            usage?: components["schemas"]["TokenUsage"];
            prompt: string;
            phase: string | null;
            activities: components["schemas"]["ArchivedActivity"][];
            text: string;
            /** @description Redacted reasoning summaries, separated by blank lines. Null or absent means none observed. */
            reasoning?: string | null;
            /** @enum {string} */
            outcome: "running" | "done" | "cancelled" | "error";
            error?: string | null;
            errorCode?: string | null;
            forkable?: boolean | null;
            terminal?: boolean | null;
            interjections?: components["schemas"]["Interjection"][];
            /** @description Interjection that started this adopted turn. */
            from_submission_id?: string | null;
        };
        ArchivedActivity: {
            /** @description Subagent identity from a delegation item or cached command turn lookup. "unknown" means the turn belongs to this run but its owner could not be resolved. Null or absent for unattributed root activity. */
            agent_id?: string | null;
            id?: string | null;
            tone: string;
            label: string;
            detail?: string | null;
            durationMs?: number | null;
            linkChatId?: string | null;
        };
        ErrorResponse: {
            /** @description Redacted steering text for a local pending chip when admission returns no_active_turn. Omitted if the chat does not exist. */
            preview_text?: string;
            error: string;
            /** @description Machine-readable failure class. "missing_keys" — chat attempted without credentials; the FE renders the inline key setup card. "unauthorized" — no valid session cookie; the FE shows the token gate. */
            code?: string;
        };
        AuthStatus: {
            auth_required: boolean;
            authenticated: boolean;
        };
        HealthResponse: {
            ok: boolean;
            has_e2b_key: boolean;
            has_openai_key: boolean;
            /** @description A dedicated executor key is configured. False means the sandbox receives the dispatcher key as CODEX_API_KEY. */
            has_executor_key: boolean;
            auth_required: boolean;
            authenticated: boolean;
        };
        ClientRequest: {
            client_id: string;
            /** @description Sidebar chat identity — backend sessions are keyed by it. */
            chat_id: string;
        };
        ChatRequest: {
            capabilities?: components["schemas"]["Capabilities"];
            client_id: string;
            /** @description Chat this turn belongs to; first turn creates its session. */
            chat_id: string;
            prompt: string;
            /** @description Optional OpenAI key for this session. Empty/omitted falls back to the host's OPENAI_API_KEY. Changing keys requires a reset first. */
            api_key?: string;
            /** @description Agent model for this chat. Binds when the first turn creates the upstream session; ignored afterwards (see SessionSnapshot.agent_locked). */
            model?: string;
            reasoning_effort?: components["schemas"]["ReasoningEffort"];
            text_verbosity?: components["schemas"]["Verbosity"];
            service_tier?: components["schemas"]["ServiceTier"];
        };
        McpCredentialStatus: {
            options: {
                [key: string]: {
                    [key: string]: string;
                };
            };
        };
        /** @description MCP servers this chat attaches. Changes reconnect the existing workspace to a replacement agent session with recent transcript context. Absent means the default selection; an empty `servers` list means none at all. */
        McpCapability: {
            /** @description Server labels from GET /api/mcp/servers, in registry order. */
            servers?: string[];
            /**
             * @description Discover MCP tools on demand instead of carrying every schema in the session's tool list.
             * @default true
             */
            tool_search: boolean;
            /** @description Config for picked gateway servers, `{label: {optionKey: value}}` (API keys mostly; the keys come from McpServerInfo.options). Sent through POST /api/mcp/credentials and resolved in backend memory; legacy clients may also provide inline values. Every response and persisted record masks values to `•`. */
            options?: {
                [key: string]: {
                    [key: string]: string;
                };
            };
        };
        McpOption: {
            /** @description Field name in the server's config object, e.g. `apiKey`. */
            key: string;
            /** @description The gateway cannot start the server without it. */
            required: boolean;
            description: string;
            /** @description Looks like a credential; render as a password field. */
            secret: boolean;
        };
        McpServerInfo: {
            /** @description Stable id sent back in capabilities.mcp.servers. */
            label: string;
            /** @description Display name for the picker row. */
            name: string;
            description: string;
            /**
             * @description service - the Agents API dials the server over HTTP. environment - the sandbox spawns it as a stdio subprocess. gateway - E2B's hosted catalog (every server the installed SDK knows), served by mcp-gateway on sandbox loopback with the chat's option values as config; every picked gateway server shares one authenticated `e2b_gateway` tool entry.
             * @enum {string}
             */
            connection_origin: "service" | "environment" | "gateway";
            /** @description True for environment- and gateway-origin servers. */
            runs_in_sandbox: boolean;
            /** @description HTTP endpoint for service-origin servers, else null. */
            server_url?: string | null;
            /** @description Config fields the server accepts; empty for service/environment servers. */
            options: components["schemas"]["McpOption"][];
            /** @description At least one required option. False marks the "free" servers that work with no values at all. */
            needs_config: boolean;
            /** @description Image cached in the executor template, so it starts instantly; other gateway servers pull on first use. */
            prepulled: boolean;
            /** @description Command line that starts the server in the sandbox, else null. */
            launch?: string | null;
        };
        Delegation: {
            /** @default false */
            enabled: boolean;
            /** @default 3 */
            max_agents: number;
        };
        MemoryEntry: {
            id: string;
            text: string;
            tags: string[];
            source_chat_id: string;
            /** Format: date-time */
            created_at: string;
        };
        /** @description Creation-time settings, copied on fork. Absent means all disabled. Changes are ignored once agent_locked is true. */
        Capabilities: {
            delegation?: components["schemas"]["Delegation"];
            mcp?: components["schemas"]["McpCapability"];
            memory?: {
                /** @default false */
                enabled: boolean;
            };
            reasoning_summary?: {
                /** @default false */
                enabled: boolean;
            };
        };
        /** @enum {string} */
        ReasoningEffort: "none" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max";
        /** @enum {string} */
        Verbosity: "low" | "medium" | "high";
        /**
         * @description OpenAI processing tier: auto (default routing), default (standard), flex (cheaper, slower, queued), priority (faster, premium).
         * @enum {string}
         */
        ServiceTier: "auto" | "default" | "flex" | "priority";
        ModelInfo: {
            /** @description OpenAI model id (e.g. gpt-5.6-sol). */
            id: string;
            /** @description Unix seconds, straight from GET /v1/models. */
            created: number;
        };
        ResumeResponse: {
            ok: boolean;
            /** @description The chat's backend context is live again. */
            resumed: boolean;
            /** @description The upstream session is gone. Prompts are disabled, but a retained workspace may still be recovered through a fork. */
            expired: boolean;
            session: components["schemas"]["SessionSnapshot"];
        };
        /** @description Open means not closed. Counts remain unknown after any stream re-attach for the rest of the run. */
        Subagents: {
            open: number | null;
            known: boolean;
        };
        /** @description Mirrors session_snapshot() in app.py. */
        SessionSnapshot: {
            /** @description Saved selection waiting for the current turn or reconnect to finish. */
            pending_mcp?: components["schemas"]["McpCapability"] | null;
            /** @description Last MCP update failure; the previous selection remains active. */
            mcp_update_error?: string | null;
            subagents?: components["schemas"]["Subagents"];
            capabilities?: components["schemas"]["Capabilities"];
            /** @description Session trace link only when a verified URL template is configured. */
            trace_url?: string | null;
            chat_id: string | null;
            /** @description Agents API session exists and the sandbox executor is alive. */
            connected: boolean;
            /** @description The chat's sandbox is snapshotted; a resume reattaches it. */
            paused: boolean;
            session_id: string | null;
            environment_id: string | null;
            executor_pid: number | null;
            /** @description A turn is currently running. */
            active: boolean;
            cancel_ready: boolean;
            /** @description E2B sandbox id. */
            sandbox: string | null;
            workspace: string;
            model: string;
            reasoning_effort: components["schemas"]["ReasoningEffort"] | null;
            verbosity: components["schemas"]["Verbosity"] | null;
            service_tier: components["schemas"]["ServiceTier"] | null;
            /** @description The upstream session exists, so the agent config (model, reasoning, verbosity, tier) is fixed — the pickers should be read-only. */
            agent_locked: boolean;
            /** @description The host has a fallback OPENAI_API_KEY configured. */
            env_key_available: boolean;
            /**
             * Format: date-time
             * @description When the live sandbox will hit its timeout and auto-pause — SandboxInfo.end_at straight from the E2B SDK. Null unless connected.
             */
            timeout_at: string | null;
            /**
             * @description Why this thread can no longer accept turns. Its sandbox remains available for a recovery fork.
             * @enum {string|null}
             */
            terminal_reason: "expired" | "decayed" | null;
        };
        WorkspaceEntry: {
            /** @description Workspace-relative path. */
            path: string;
            /** @enum {string} */
            kind: "file" | "directory";
            /** @description Bytes for files, null for directories. */
            size: number | null;
            /** @description Modification time in nanoseconds since the epoch. */
            modified: number;
        };
        LogStreamEvent: components["schemas"]["LogRecordEvent"] | components["schemas"]["LogGapEvent"] | components["schemas"]["LogClosedEvent"];
        LogRecordEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "log";
            /** @description Changes when backend log history is replaced. */
            stream_id: string;
            cursor: number;
            seq: number;
            /** Format: date-time */
            at: string;
            /** @enum {string} */
            source: "backend" | "executor" | "agents_command";
            /** @enum {string} */
            stream: "stdout" | "stderr" | "combined";
            text: string;
            turn_id?: string | null;
            item_id?: string | null;
            output_index?: number | null;
        };
        LogGapEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "gap";
            dropped_through_seq: number;
            available_from: number;
        };
        LogClosedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "closed";
            /** @enum {string} */
            reason: "reset" | "shutdown";
        };
        ChatEvent: components["schemas"]["InterjectionEvent"] | components["schemas"]["TurnStartedEvent"] | components["schemas"]["StateEvent"] | components["schemas"]["ActivityEvent"] | components["schemas"]["DeltaEvent"] | components["schemas"]["TextEvent"] | components["schemas"]["ReasoningEvent"] | components["schemas"]["DoneEvent"] | components["schemas"]["CancelledEvent"] | components["schemas"]["ErrorEvent"] | components["schemas"]["UsageEvent"];
        InterjectionEvent: components["schemas"]["Interjection"] & {
            /** @constant */
            type: "interjection";
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "interjection";
        };
        /** @description Ends the previous archived turn and starts an adopted root within the same run. The run remains active until the stream ends. */
        TurnStartedEvent: {
            previous_turn_id?: string | null;
            previous_usage?: components["schemas"]["TokenUsage"] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "turn_started";
            prompt: string;
            from_submission_id: string;
            /** @enum {string} */
            previous_outcome: "done" | "error";
            previous_error?: string | null;
        };
        /** @description Turn lifecycle phase transition. */
        StateEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "state";
            /** @enum {string} */
            phase: "starting" | "creating" | "connecting" | "resuming" | "running";
            message: string;
        };
        /** @description One agent activity timeline entry (command, file change, tool call…). Events sharing an `id` describe the same item over time (started → finished) — the UI updates that row in place instead of appending. */
        ActivityEvent: {
            /** @description Subagent identity from a delegation item or cached command turn lookup. "unknown" means the turn belongs to this run but its owner could not be resolved. Null or absent for unattributed root activity. */
            agent_id?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "activity";
            /** @description Upstream item id; null for lifecycle rows (turn/session). */
            id?: string | null;
            /** @enum {string} */
            tone: "connected" | "error" | "turn" | "running" | "done" | "cancelled" | "approval" | "idle" | "item";
            label: string;
            detail?: string | null;
            duration_ms?: number | null;
        };
        /** @description Incremental agent output text. */
        DeltaEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "delta";
            text: string;
        };
        /** @description Full output text. Sent when no deltas were streamed, or after a stalled / closed stream to replace a cut-short answer with the retained message. The UI replaces the turn's text instead of appending. */
        TextEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            text: string;
        };
        /** @description Redacted reasoning summary text. Append delta or replace the entire turn's reasoning with text to repair missed or interleaved deltas. */
        ReasoningEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "reasoning";
        } & ({
            delta: string;
        } | {
            text: string;
        });
        /** @description Terminal — turn finished; snapshot reflects the reusable session. */
        DoneEvent: {
            /** @description All root turns and steering reconciliation have finished; deferred usage may follow. */
            run_complete?: boolean;
            /** @description Upstream root turn identity. */
            turn_id?: string;
            usage?: components["schemas"]["TokenUsage"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "done";
            status: string;
            session: components["schemas"]["SessionSnapshot"];
        };
        /** @description Terminal — turn cancelled (session may or may not survive). */
        CancelledEvent: {
            /** @description All root turns and steering reconciliation have finished; deferred usage may follow. */
            run_complete?: boolean;
            /** @description Upstream root turn identity. */
            turn_id?: string;
            usage?: components["schemas"]["TokenUsage"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "cancelled";
            session: components["schemas"]["SessionSnapshot"];
        };
        /** @description Terminal — turn failed. Established chats survive a failed turn and stay retryable; code=expired means the upstream session is gone and code=expired means the upstream session is gone; code=decayed means the upstream session still retrieves as idle but can no longer run turns (post-idle decay). Both are terminal; when forkable=true the retained workspace can be cloned into a fresh sibling chat. */
        ErrorEvent: {
            /** @description All root turns and steering reconciliation have finished; deferred usage may follow. */
            run_complete?: boolean;
            /** @description Upstream root turn identity. */
            turn_id?: string;
            usage?: components["schemas"]["TokenUsage"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            message: string;
            /**
             * @description Machine-readable failure class.
             * @enum {string}
             */
            code?: "expired" | "decayed";
            /** @description Source workspace can be cloned into a fresh chat. */
            forkable?: boolean;
            /** @description Current thread must no longer accept prompts. */
            terminal?: boolean;
        };
        /** @description Root-agent tokens. Missing counters are omitted; cached and reasoning are contained subsets. */
        TokenUsage: {
            input_tokens?: number;
            input_tokens_details?: {
                cached_tokens?: number;
            };
            output_tokens?: number;
            output_tokens_details?: {
                reasoning_tokens?: number;
            };
            total_tokens?: number;
        };
        /** @description Deferred root usage retrieved after a terminal outcome; replaces usage for this turn. */
        UsageEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "usage";
            turn_id: string;
            usage: components["schemas"]["TokenUsage"];
        };
    };
    responses: {
        /** @description Acknowledged. */
        Ok: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    ok: boolean;
                };
            };
        };
        /** @description Error envelope. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Browser-generated client id, 8-80 chars of [A-Za-z0-9_-]. */
        ClientIdHeader: string;
        /** @description Chat whose sandbox to read. */
        ChatIdQuery: string;
        /** @description Last received log sequence. Omit to replay retained history. */
        LogCursorQuery: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMemories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shared memory entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entries: components["schemas"]["MemoryEntry"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    deleteMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getChatArchive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transcripts and sidebar metadata for this workbench. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        chats: components["schemas"]["ArchivedChat"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    importChatArchive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    chats: components["schemas"]["ArchivedChat"][];
                };
            };
        };
        responses: {
            200: components["responses"]["Ok"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            413: components["responses"]["Error"];
        };
    };
    postFork: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientRequest"] & {
                    promote?: boolean;
                    sibling?: boolean;
                };
            };
        };
        responses: {
            /** @description Connected child sandbox and copied transcript. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        chat: components["schemas"]["SessionSnapshot"];
                        archive: components["schemas"]["ArchivedChat"];
                    };
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    getAuthStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Auth state for this browser. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    postAuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description Session established; cookie set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        authenticated: boolean;
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    postAuthLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cookie cleared. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        authenticated: boolean;
                    };
                };
            };
        };
    };
    postAuthInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One-time login URL. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        url: string;
                        /** @description Seconds until the token expires. */
                        expires_in: number;
                    };
                };
            };
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    postKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    e2b_api_key?: string;
                    /** @description Dispatcher key — backend process only. */
                    openai_api_key?: string;
                    /** @description Executor key, handed to the sandbox as CODEX_API_KEY. Optional; unset means the executor reuses the dispatcher key. */
                    openai_executor_api_key?: string;
                };
            };
        };
        responses: {
            /** @description Updated credential presence. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest-first model ids. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        models: components["schemas"]["ModelInfo"][];
                    };
                };
            };
            502: components["responses"]["Error"];
        };
    };
    getMcpCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Masked options, never credential values. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpCredentialStatus"];
                };
            };
        };
    };
    saveMcpCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    server: string;
                    /** @description Keep unchanged credentials already configured for this chat. */
                    chat_id?: string;
                    options: {
                        [key: string]: string;
                    };
                };
            };
        };
        responses: {
            /** @description Configured fields, with values masked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpCredentialStatus"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    setMcpSelection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    chat_id: string;
                    client_id: string;
                    mcp: components["schemas"]["McpCapability"];
                };
            };
        };
        responses: {
            /** @description Updated chat snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description MCP selection saved for automatic application after the current turn. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    getMcpServers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog in registry order, plus the default selection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        servers: components["schemas"]["McpServerInfo"][];
                        /** @description Labels a chat attaches when it picks nothing. */
                        default: string[];
                    };
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: {
                /** @description Chat to inspect; omitted or unknown yields an all-null snapshot. */
                chat_id?: string;
            };
            header: {
                /** @description Browser-generated client id, 8-80 chars of [A-Za-z0-9_-]. */
                "X-Demo-Client-ID": components["parameters"]["ClientIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session snapshot (all-null fields when no session exists). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    postChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description SSE stream of ChatEvent JSON payloads. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ChatEvent"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getLogs: {
        parameters: {
            query: {
                /** @description Chat whose sandbox to read. */
                chat_id: components["parameters"]["ChatIdQuery"];
                /** @description Last received log sequence. Omit to replay retained history. */
                cursor?: components["parameters"]["LogCursorQuery"];
            };
            header: {
                /** @description Browser-generated client id, 8-80 chars of [A-Za-z0-9_-]. */
                "X-Demo-Client-ID": components["parameters"]["ClientIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of LogStreamEvent JSON payloads. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["LogStreamEvent"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    postResume: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientRequest"];
            };
        };
        responses: {
            /** @description Resume outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            400: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    postPause: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientRequest"];
            };
        };
        responses: {
            /** @description Pause outcome with the resulting snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                        session: components["schemas"]["SessionSnapshot"];
                    };
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    postSteer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SteerRequest"];
            };
        };
        responses: {
            /** @description Existing or newly admitted interjection. Status does not imply application. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Interjection"];
                };
            };
            400: components["responses"]["Error"];
            /** @description no_active_turn; nothing was admitted. The client retries admission with the same submission ID while the run is active (up to 120 seconds), or sends as a normal prompt once the run is idle. Stop cancels the wait. Includes a redacted preview_text when the chat exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            502: components["responses"]["Error"];
        };
    };
    postCancel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientRequest"];
            };
        };
        responses: {
            200: components["responses"]["Ok"];
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    postReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientRequest"];
            };
        };
        responses: {
            200: components["responses"]["Ok"];
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    getFiles: {
        parameters: {
            query: {
                /** @description Chat whose sandbox to read. */
                chat_id: components["parameters"]["ChatIdQuery"];
            };
            header: {
                /** @description Browser-generated client id, 8-80 chars of [A-Za-z0-9_-]. */
                "X-Demo-Client-ID": components["parameters"]["ClientIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace entries (files and directories, capped at 300). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        files: components["schemas"]["WorkspaceEntry"][];
                        workspace: string;
                    };
                };
            };
            403: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    getFile: {
        parameters: {
            query: {
                /** @description Chat whose sandbox to read. */
                chat_id: components["parameters"]["ChatIdQuery"];
                /** @description Workspace-relative path (no leading slash). */
                path: string;
            };
            header: {
                /** @description Browser-generated client id, 8-80 chars of [A-Za-z0-9_-]. */
                "X-Demo-Client-ID": components["parameters"]["ClientIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content. Text is UTF-8 with the session API key redacted; images (png/jpeg/gif/webp) and videos (mp4/m4v/webm/mov) come back base64-encoded with their mime type. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        path: string;
                        content: string;
                        /** @enum {string} */
                        encoding: "utf-8" | "base64";
                        /** @description Present only for base64 image/video payloads. */
                        mime?: string;
                    };
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            413: components["responses"]["Error"];
            415: components["responses"]["Error"];
        };
    };
    postUpload: {
        parameters: {
            query: {
                /** @description Chat whose sandbox to read. */
                chat_id: components["parameters"]["ChatIdQuery"];
            };
            header: {
                /** @description Browser-generated client id, 8-80 chars of [A-Za-z0-9_-]. */
                "X-Demo-Client-ID": components["parameters"]["ClientIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    files: string[];
                };
            };
        };
        responses: {
            /** @description Workspace-relative paths that were written. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        written: string[];
                    };
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            413: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
}
